### ISSUE TITLE
research-maps.html depends on openlayers via http

### ISSUE THREAD

**Issue by rraub** [gios-asu/gios-research-maps#3]
I made a gh-pages branch to get the io pages working and it looks like https://gios-asu.github.io/gios-research-maps/html/research-maps.html isn't working because its asking for openlayers over http. Could we find an https source to use instead?

**Comment by chasethenag420** [comment]
Openlayers doens't provide https so we might need to download their library from github.

**Comment by rraub** [comment]
What about https://cdnjs.com/libraries/ol3 ?

**Comment by chasethenag420** [comment]
It worked..thanks

**Comment by rraub** [comment]
sure thing, if you could merge your changes into the gh-pages branch and the github io pages will auto update with the latest code.
