### ISSUE TITLE
Plot the points from where people's degrees are from

### ISSUE THREAD

**Issue by rraub** [gios-asu/gios-research-maps#47]
Mainly to see how that looks on a map and if it is worth while.

The degree locations will come from the people_achievement table in our gios db, I can help export these for you. However we will need to geocode them since they are just place names.

**Comment by rraub** [comment]
Very cool! 
<img width="790" alt="screen shot 2016-01-13 at 3 12 25 pm" src="https://cloud.githubusercontent.com/assets/295804/12309478/33349a5e-ba08-11e5-8d6f-57bf66c66fda.png">

**Comment by chasethenag420** [comment]
But I see one problem with line strings.. here if we click near the tempe
area all the linestrings that are intersecting near tempe but originated
somewhere also shows up which is kind of doesn't provide information if
some one want to see who all are from tempe.


Thanks & Regards,
Nagarjuna Myla,
Ph no: 480-277-4595.

**Comment by chasethenag420** [comment]
Hi gios-asu/gios-resear,

I'd like to add you to my professional network on LinkedIn.

- Nagarjuna

Confirm that you know Nagarjuna: https://www.linkedin.com/e/v2?e=0-ijdieppk-as&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=OuZ_f_0k&invitationId=6093194567786516480








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ijdieppk-as&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGUA9T7LumU3gAAAVI9gN_QMFUWy28zv7YNWhWkfwJa1fPkjSO7-wdWNoBL9uGE78Ctza6Mnh_jYa5U7qCsAGqXk_qgLo4QdKB7St5UXYMiE5phYL1Vy5IMIq0xvELlisJ1LORQpvLJ2QkwZNMVplLmbEKplGXAtsaGEMzQlASWfn-09aoVJ5ExyCTJBDyl48ux&eid=0-ijdieppk-as


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ijdieppk-as&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Nagarjuna Myla would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-q2z0is-ijn3toy2-3b&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=OuZ_f_0k&invitationID=6093194567786516480

View Nagarjuna Myla&#39;s profile: https://www.linkedin.com/e/v2?e=-q2z0is-ijn3toy2-3b&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=OuZ_f_0k&invitationID=6093194567786516480





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q2z0is-ijn3toy2-3b&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-q2z0is-ijn3toy2-3b&loid=AQGgJMhT91S_mAAAAVJg3Dni09gHMdr3wD_uDcxcH8Td8SL1_cYby-PS5BchKvt7_ajXvlrfA2iZEYDh0cH6XT_ui2nMhZWogoyB0tfuW1a6AaBz9CVj0E6roZ1Bn-dxbysAcCBrJbWS62Bbyi5FKG_qAIs4Y20_3aOfJQkcPgQDqu-JSWUKW4cCDQ73tqEMnVLu

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q2z0is-ijn3toy2-3b&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by chasethenag420** [comment]
Nagarjuna Myla would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-q2z0is-ijx3mdrp-sl&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=OuZ_f_0k&invitationID=6093194567786516480

View Nagarjuna Myla&#39;s profile: https://www.linkedin.com/e/v2?e=-q2z0is-ijx3mdrp-sl&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=OuZ_f_0k&invitationID=6093194567786516480





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q2z0is-ijx3mdrp-sl&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-q2z0is-ijx3mdrp-sl&loid=AQFrXr3Fvi_vywAAAVKE41KeE8PjjE42A5qJzrqxy10QnwLMJFajA85-BBS0_MShqfWhRYPYYCxyTDkrmRVcKNCTMQfi4YlXyNtPcv19HFxHc3KvZDVpxzDyiviDNoYk0lGLgLMssWe4jbF1NaQLCRN13-DhOliyaQW3dqOP3MyK54KFPNGRy0ijeakW_nQnZcNM

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q2z0is-ijx3mdrp-sl&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rraub** [comment]
@chasethenag420 your linkedin requests are going crazy!

**Comment by chasethenag420** [comment]
Sorry for the trouble ..Just now successfully cancelled all sent
invitations so no more spamming.


Thanks & Regards,
Nagarjuna Myla,
Ph no: 480-277-4595.
