### ISSUE TITLE
change basemap to the same one that github uses

### ISSUE THREAD

**Issue by rraub** [gios-asu/gios-research-maps#6]
Or similar.

**Comment by idmontie** [comment]
:+1: :octocat:

**Comment by chasethenag420** [comment]
https://www.mapbox.com/developers/vector-tiles/

We have different base maps or else we can create own and publish it using mapbox studio.
`https://www.mapbox.com/developers/api/maps/#mapids`

Below one looks close to one we saw on github but not exactly same
`https://api.mapbox.com/v4/mapbox.streets-basic/0/0/0.png?access_token=pk.eyJ1IjoiY2hhc2V0aGVuYWc0MjAiLCJhIjoiY2lnNDhibThiMmZ2a3YzbTNza283dDd4cyJ9.UGgEZnwV7A5PQl5TZ2lV_Q`

Github map also works with this URL but I am not sure if we can use it here access token I used is same as above one which if default.

`https://b.tiles.mapbox.com/v4/github.kedo1cp3/1/0/1.png?access_token=pk.eyJ1IjoiY2hhc2V0aGVuYWc0MjAiLCJhIjoiY2lnNDhibThiMmZ2a3YzbTNza283dDd4cyJ9.UGgEZnwV7A5PQl5TZ2lV_Q`

**Comment by rraub** [comment]
Ok, so we can just sign up for the MapBox "starter pack" once we're ready to go live. I think thats fine, we should be well under the request limits.
